---
- name: Install Powerlevel10k theme
  become_user: "{{ ansible_user }}"
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Symbolic link .p10k.zsh from Dotfiles
  #become_user: "{{ ansible_user }}"
  become: true
  file:
    src: "{{ role_path }}/files/.p10k.zsh"
    dest: "~/.p10k.zsh"
    state: link
