---
- name: Install required dependencies
  become: true
  apt:
    name: zsh
    state: present

- name: Symbolic link .zshrc from Dotfiles
  become_user: "{{ ansible_user }}"
  file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    state: link
    force: true

- name: Change default shell
  user:
    name: "{{ ansible_user }}"
    shell: "/bin/zsh"
