---
- name: Install required dependencies
  become: true
  apt:
    name: zsh
    state: present

- name: Symbolic link .zshrc from Dotfiles
  #become_user: "{{ ansible_user }}"
  become: true
  file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "~/.zshrc"
    state: link

- name: Change default shell
  user:
    name: "{{ ansible_user }}"
    shell: "/bin/zsh"
