---
- name: Download and install Oh My Zsh
  become_user: "{{ ansible_user }}"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh )"
  args:
    creates: "~/.oh-my-zsh"

# Plugins
- name: Install zsh-syntax-highlighting plugin
  become_user: "{{ ansible_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Install zsh-autosuggestions plugin
  become_user: "{{ ansible_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-completions plugin
  become_user: "{{ ansible_user }}"
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: "~/.oh-my-zsh/custom/plugins/zsh-completions"
