---
- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Import Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
# - name: Create the /etc/apt/keyrings directory
#   file:
#     path: /etc/apt/keyrings
#     state: directory
#     mode: "0755"

# - name: Download and dearmor the Docker GPG key in one task
#   shell:
#     cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: true

- name: Install Docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
