---
- name: Install Neovim dependencies
  become: true
  apt:
    deb: https://github.com/neovim/neovim/releases/download/v0.8.3/nvim-linux64.deb
    state: present

- name: Git clone Packer
  become_user: "{{ ansible_user }}"
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1

- name: Create ~/.config/nvim
  file:
    path: "~/.config/nvim/"
    state: directory
    mode: "0755"

- name: Symbolic link nvim from Dotfiles
  #become_user: "{{ ansible_user }}"
  become: true
  file:
    src: "{{ role_path }}/files/nvim"
    dest: "~/.config/nvim"
    state: link
    force: true
